@startuml
'skinparam linetype ortho
'skinparam linetype polyline
'left to right direction
'top to bottom direction

skinparam nodesep 45
skinparam ranksep 45


class GuiView {
    - GUI gui
    - LangController langController
    + int promptChoice(Message,Message)
    + void showMessage(Message)
    + void update(Player[],Field[],DiceCup)
}


package controller {
    class GameController {
        - View view
        - GameBoard gameBoard
        - UserIO userIO
        + void playGame()
    }
    class UserIO {
        ~ BasicUserIO basicUserIO
        + boolean promptYesOrNo(Message)
        + boolean promptBuyField(String,String)
        ~ int promptChoice(Message,Message)
        ~ void showMessage(Message)
    }
    interface BasicUserIO {
        ~ int promptChoice(Message,Message)
        ~ void showMessage(Message)
    }
}
package lang {
    class LangController {
        - EnumMap<Type, String> langMap
        + String getMessage(Message)
    }
    class Message {
        - String[] args
        - Type type
        + {static} Message of(Type,String)
        + {static} Message buyHouse(String)
        + {static} Message yes()
        + {static} Message no()
    }
    enum Type {
        +  WANT_TO_BUY_HOUSE
        +  YES
        +  NO
    }
}
'GuiView .up.|> BasicUserIO
'GuiView *-- LangController
'UserIO .down.|> BasicUserIO
'GameController *-right- UserIO

'LangController *.left. Message

'Message +-- Type

GameController *-- UserIO
UserIO ..|> BasicUserIO

GuiView .left.|> BasicUserIO
LangController-down-* GuiView

LangController *.up. Message
Message +-up- Type
@enduml
